name: CI retry mock 

on:        
  workflow_dispatch:

jobs:
  invoke-rerun-workflow:
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache if success
        id: workflow-rerun
        uses: actions/cache@v2
        with:
          path: |
            VERSION
          key: workflow-rerun-${{ github.run_id }}
      - name: Trigger re-run workflow
        if: steps.workflow-rerun.outputs.cache-hit != 'true'
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: re-run workflow
          token: ${{ secrets.REPO_WRITE_ACCESS_TOKEN }}
          inputs: '{ "owner": "vastin", "repository": "aws-otel-collector", "runid": "${{ github.run_id }}" }'

      - name: Cache if success
        if: steps.workflow-rerun.outputs.cache-hit == 'true'
        id: workflow-rerun-2
        uses: actions/cache@v2
        with:
          path: |
            VERSION
          key: workflow-rerun-${{ github.run_id }}
      - name: Trigger re-run workflow
        if: steps.workflow-rerun.outputs.cache-hit == 'true' && steps.workflow-rerun-2.outputs.cache-hit != 'true'
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: re-run workflow
          token: ${{ secrets.REPO_WRITE_ACCESS_TOKEN }}
          inputs: '{ "owner": "vastin", "repository": "aws-otel-collector", "runid": "${{ github.run_id }}" }'


  fail-test:
    runs-on: [ubuntu-latest]
    steps:
      - name: step1
        run: |
          echo step1
      # - name: sleep more than 5 mins
      #   run: |
      #     sleep 400
      - name: step2 # the fail step
        run: |
          fail
