name: re-run workflow

on:        
  workflow_dispatch:
    inputs:
      owner:
        description: 'repository owner name'
        required: true
      repository:
        description: 'repository name'
        required: true
      runid:
        description: 'workflow run id'
        required: true

env:
  GITHUB_TOKEN: ${{ secrets.REPO_WRITE_ACCESS_TOKEN }}

jobs:
  re-run-workflow: 
    runs-on: ubuntu-latest
    steps: 
      # - name: Checkout
      #   uses: actions/checkout@v2

      # - name: Cache if success
      #   id: workflow-rerun
      #   uses: actions/cache@v2
      #   with:
      #     path: |
      #       VERSION
      #     key: workflow-rerun-${{ github.event.inputs.runid }}

      # - name: Re-run workflow
      #   if: steps.workflow-rerun.outputs.cache-hit != 'true'
      #   run: |
      #     pip3 install ghapi
      #     python3 tools/workflow/rerun_workflow.py ${{ github.event.inputs.owner }} ${{ github.event.inputs.repository }} ${{ github.event.inputs.runid }}

      - name: Re-run workflow
        run: |
          pip3 install ghapi
          python3 tools/workflow/rerun_workflow.py ${{ github.event.inputs.owner }} ${{ github.event.inputs.repository }} ${{ github.event.inputs.runid }}

