name: re-run workflow

on:        
  workflow_dispatch:
    inputs:
      repo:
        description: 'owner/repository'
        required: true
      runid:
        description: 'workflow run id'
        required: true

env:
  GITHUB_TOKEN: ${{ secrets.REPO_WRITE_ACCESS_TOKEN }}

jobs:
  re-run-workflow: 
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2

      - name: Re-run workflow
        run: |
          pip3 install ghapi
          repo_info={{ github.event.inputs.repo }}
          params=(${repo_info//// })
          echo "owner =" ${params[0]}
          echo "repository =" ${params[1]}
          python3 tools/workflow/rerun_workflow.py ${params[0]} ${params[1]} ${{ github.event.inputs.runid }}

